#!/bin/sh
 
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
 
echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"

for f in *.ko; do
    insmod $f
done

echo "hello sgpu!" > /dev/sgpu/sgpu

exec /bin/sh
